test_that("config exposes the bioconda constants", {
  expect_equal(PUBLISH_REPO, "r-observatory/bioconda-downloads")
  expect_equal(DATA_SOURCE, "bioconda")
  expect_equal(DAILY_TABLE, "bioconda_downloads_daily")
  expect_equal(SUMMARY_TABLE, "bioconda_downloads_summary")
  expect_true(LOAD_BIOC_MAP)
  expect_identical(NAME_PREFIXES, c("r-", "bioconductor-"))
  expect_equal(RECENT_WINDOW, 400L)
  expect_equal(REVISION_WINDOW, 10L)
  expect_true(all(c("origin", "canonical_name") %in% SUMMARY_COLS))
})
